### ISSUE TITLE
Are the following data types missing？

### ISSUE THREAD

**Issue by j1822240581** [s7connector/s7connector#106]
1.Is this project applicable to S7 Series, including s71200 / 1500
2.Missing Sint, LREAL and other data types in s7type

**Comment by BuckarooBanzay** [comment]
> 1.Is this project applicable to S7 Series, including s71200 / 1500

This may or may not work, the library predates those models i think,
please feel free to test it out and report back here :wink: 

> 2.Missing Sint, LREAL and other data types in s7type

PR's accepted :shrug:
