### ISSUE TITLE
 Do we have a disconnection and reconnection mechanism? I didn't see the API

### ISSUE THREAD

**Issue by 6triker** [s7connector/s7connector#156]
If Inscribe

**Comment by BuckarooBanzay** [comment]
there's no reconnection mechanism, but you can disconnect with this:

https://github.com/s7connector/s7connector/blob/9aa87120f1a7d443e90e14f7b8600448719537a1/src/main/java/com/github/s7connector/impl/S7TCPConnection.java#L103

**Comment by nanwang1986** [comment]
> there's no reconnection mechanism, but you can disconnect with this:
> 
> https://github.com/s7connector/s7connector/blob/9aa87120f1a7d443e90e14f7b8600448719537a1/src/main/java/com/github/s7connector/impl/S7TCPConnection.java#L103


reconnect need modify 3 .java，we need close old socket and new another socket to reconnect，and S7Connection method readBytes lock semaphore release not in finally block，so，it can make this lock not release
