### ISSUE TITLE
Modify README

### ISSUE THREAD

**Issue by amitjoy** [s7connector/s7connector#17]
README needs to be modified in such a way that would better describe the project. I have an initial idea on how it would be.

===> **At the top of README** : _A logo for S7Connector_
===> **Just below it**: _S7 Devices image(s)_
===> _Features_ in _bullet_ points (_one line_ per bullet item)
===> _Documentation URL_
===> _Maven Support_
===> _Contributing to this Project_ (For this we need to add a link to _CONTRIBUTING.md_)

This would be really great to have the README updated in this similar way.

**Comment by amitjoy** [comment]
@thomasrudin I have prepared a preliminary README. You can see it in my fork. Let me know if I can go ahead with the pull request.

**Comment by thomasrudin** [comment]
I like the logo :smile:
A small tutorial/quickstart and pom-snippets would not hurt in there.. (i could do that)
I dont know if we can use the siemens(R)-images on there but would leave it there for now (let's see where it goes)
Can you make a pull request ?
You can also make your changes directly if you want...

**Comment by thomasrudin** [comment]
contribution in separate issue: #23
