### ISSUE TITLE
Use of word "PROFINET" instead of TCP

### ISSUE THREAD

**Issue by amitjoy** [s7connector/s7connector#27]
I am just wondering if there is any special reason of using only **_TCP Connection_** everywhere instead of **_PROFINET_**.

**Comment by thomasrudin** [comment]
I don't think the connection has anything to do with PROFINET.
PROFINET is a standard which implements realtime-transport and **incorporates** TCP/IP.
The connection to the PLC as far as i know is *only* TCP/IP...

**Comment by amitjoy** [comment]
I knew that the S7 TCP connection is named as PROFINET. Now I understand the reason of not using the name **_PROFINET_**. Thanks! 

I just have a proposal. We can even include PROFINET in the README, the same way you explained in the last comment. Just in case, people think the other way.

**Comment by amitjoy** [comment]
Would it be great to include PROFINET in the docs or README? What do you think? Just to make the library more visible to the google or github search.

**Comment by thomasrudin** [comment]
Yes, sounds good.
I include it in my next coding session :smile:
