### ISSUE TITLE
Reuse JDK 1.5's Semaphore

### ISSUE THREAD

**Issue by amitjoy** [s7connector/s7connector#30]
Instead of using custom Semaphores for concurrency, it is actually better to reuse the Java 5's inbuilt concurrent classes (Lock, ReentrantRead(Write)Lock, Semaphore etc)

**Comment by thomasrudin** [comment]
Where did i use custome semaphores??? :smile:

**Comment by amitjoy** [comment]
I have corrected the use of custom semaphore with the existing JDK 1.5's semaphore.
