### ISSUE TITLE
libnodave dependency

### ISSUE THREAD

**Issue by amitjoy** [s7connector/s7connector#37]
It is mentioned that **This project is based on libnodave** but I couldn't find sources which are originated from libnodave. Would you kindly mention the sources from libnodave?

**Comment by thomasrudin** [comment]
The Classes in com.github.s7connector.impl.nodave are imported from the libnodave project, but the headers were modified by the copyright plugin :(

https://github.com/s7connector/s7connector/tree/master/src/main/java/com/github/s7connector/impl/nodave

**Comment by thomasrudin** [comment]
created issue #38 for this
