### ISSUE TITLE
Issue with LongConverter

### ISSUE THREAD

**Issue by cpinkl** [s7connector/s7connector#42]
Hello,

May I'm wrong but i'm running into an issue with DWORD(Long)
Example:
DB2:
```
Address     |  0  |  1   |  2  |  3  |
Values(hex) |  0  |  0   |  2  |  12 | = 530

bs = connector.read(DaveArea.DB, 2, 4, 0);
final Integer i = ((bs[3] << 0) & 0x000000FF) | 
				          ((bs[2] << 8) & 0x0000FF00) | 
				          ((bs[1] << 16) & 0x00FF0000) | 
				          ((bs[0] << 24) & 0xFF000000);
```
In LongConverter.java it's the other way round. This only works with unsigned integers.

Best Regards
Christoph

**Comment by thomasrudin** [comment]
I found some issues with the LongConverter (ClassCastException).
Sadly i'm in no position to test the converter on a real PLC or set some some values there.
Can you provide some byte -> number examples?
Some positive and negative ones would be nice: -64000, -1, 0, +1, +64000 etc (and the bytes on the plc)

**Comment by cpinkl** [comment]
I don't have any PLC at the moment to test negative values but I'm on the road to setup a test environment and check all datatypes. Maybe next week it will be setup. Currently i tested your change in LongConverter and it's working for positive values with a real PLC. A first check with a simulation software with negative values in two's complement was successful. I'll come back next week with more infos.

**Comment by thomasrudin** [comment]
any new on this?

**Comment by thomasrudin** [comment]
tested manually, works AFAIK
