### ISSUE TITLE
Unexpected function code in answer

### ISSUE THREAD

**Issue by Zuendelmeister** [s7connector/s7connector#43]
Hi everyone,

I realy like this library. Unfortunately sometimes I get the following Exception:

> java.lang.IllegalArgumentException: Result: Unexpected function code in answer

In a loop I request several bytes in serial like so:

`bs0 = connector.read(DaveArea.DB, 0, 1, offset);`

Am I doing something wrong?
Thanks.

Best regards,
Zuendelmeister

**Comment by thomasrudin** [comment]
can you elaborate with a code example (Connection opening, looping) and where the error occurs?
Which plc type do you use?

**Comment by thomasrudin** [comment]
I think i had the same issue on an S7-1200.
I specified the rack and slot numbers and got a working connection:
```java
S7ConnectorFactory
				.buildTCPConnector()
				.withHost("10.0.0.XX")
				.withRack(2) //defaults to 0
				.withSlot(0) //defaults to 2
				.build();
```

**Comment by Zuendelmeister** [comment]
Hi @thomasrudin,
thanks for your update. I tried that also but unfortunately it did not work.
Now I just read all the bytes I need at once and that seems to help.

Best regards,
Zuendelmeister

**Comment by thomasrudin** [comment]
Alternatively you could use the [Bean Serializer](http://htmlpreview.github.io/?https://github.com/s7connector/s7connector/blob/master/index.html#Bean%20serializer%20tutorial) and create a DAO class. This way all necessary bytes are read behind the scenes and you could use the relevant bits

**Comment by thomasrudin** [comment]
Closing and documenting the limitation in [Compatibility table](http://htmlpreview.github.io/?https://github.com/s7connector/s7connector/blob/master/index.html#Compatibility)
