### ISSUE TITLE
IllegalArgumentException when trying to dispense an array of byte

### ISSUE THREAD

**Issue by jreimone** [s7connector/s7connector#44]
In our code base we use your (great) library to dispense from a bean class. It contains a field specified like this

		@S7Variable(type = S7Type.BYTE, byteOffset = 0, bitOffset = 0, arraySize = 10)
		public byte[] ourField = new byte[10];

We took your example as base:
https://github.com/s7connector/s7connector/blob/d2877d5ee09392e82a13f1b311dac4fec0abaed2/src/test/java/com/github/s7connector/test/SerializerByteArrayTest.java#L80

But, when trying to dispense to that bean we get an IllegalArgumentException for that field. We found out that we had to use the type `Byte` instead of the primitive `byte`. Can you confirm/fix that?

**Comment by thomasrudin** [comment]
Yes, thats actually a limitation of the java reflection api, the test-case in question is thus marked as `@Ignore`. Its not clearly written in the documentation.

I opened the issue to recheck the current api state and documentation here: #45

Does the workaround with Byte[] work for you?

**Comment by jreimone** [comment]
Yes of course, that works for us.

**Comment by thomasrudin** [comment]
Closed with issue: #45
