### ISSUE TITLE
Error on Serializing an Object

### ISSUE THREAD

**Issue by a13u** [s7connector/s7connector#47]
Hi!
I use the following code:

		S7Serializer serializer = S7SerializerFactory.buildSerializer(connector);
		
		MyDataBean bean1 = new MyDataBean();
		
		//Set some values
		bean1.bit1 = true;
		bean1.myNumber = 123;
		

		serializer.store(bean1, 1, 23);
		
		MyDataBean bean2 = serializer.dispense(MyDataBean.class, 1, 23); //here the error occurs

I always get the error: on  
Exception in thread "main" com.github.s7connector.exception.S7Exception: dispense
	at com.github.s7connector.impl.serializer.S7SerializerImpl.dispense(S7SerializerImpl.java:145)
	at HelloWorld.main(HelloWorld.java:84)
Caused by: java.lang.IllegalArgumentException: Result: the desired address is beyond limit for this PLC
	at com.github.s7connector.impl.S7BaseConnection.checkResult(S7BaseConnection.java:55)
	at com.github.s7connector.impl.S7BaseConnection.read(S7BaseConnection.java:101)
	at com.github.s7connector.impl.serializer.S7SerializerImpl.dispense(S7SerializerImpl.java:142)
	... 1 more

Do I have to configure anything in the TIA portal? Currently I have 7 int variables in the datablock. I decided to use the offest 23 to avoid any conflicts. Even if the "store" operation does not throw an error I can not see anything in the TIA Portal in the Monitor mode....

Thank you!

**Comment by thomasrudin** [comment]
Can you share the definition of the MyDataBean class...?

**Comment by a13u** [comment]
Its identical to the test code:
https://github.com/s7connector/s7connector/tree/master/src/test/java/com/github/s7connector/test/example

**Comment by a13u** [comment]
Before, I worked with S7Netplus: Here I was forced to modify DB-Properties (see the last two pages of the manual https://github.com/S7NetPlus/s7netplus/blob/master/Documentation/Documentation.pdf).

Probably this causes the issue? (Currently I have no SPS with me - I will try it when I return home)

**Comment by a13u** [comment]
Unfortunatly, I still get the same error (I created a complete new block (DB2, without any variables, S7 1200) and use the following code):
import com.github.s7connector.api.annotation.S7Variable;
import com.github.s7connector.impl.utils.S7Type;

public class MyDataBean {
	@S7Variable(byteOffset=0, bitOffset=0, type=S7Type.BOOL)
	public boolean bit1;
	
	@S7Variable(byteOffset=0, bitOffset=1, type=S7Type.BOOL)
	public boolean bit2;
	
	@S7Variable(byteOffset=1, type=S7Type.BYTE)
	public byte someByte;
	
	@S7Variable(byteOffset=2, type=S7Type.WORD)
public int myNumber;
}



	    
		//Create serializer
		S7Serializer serializer = S7SerializerFactory.buildSerializer(connector);
		
		//dispense bean from DB100 and offset 0
		MyDataBean bean1 = serializer.dispense(MyDataBean.class, 1, 23);
		
		//Set some values
		bean1.bit1 = true;
		bean1.myNumber = 123;
		
		//Store bean to DB101 offset 0
		serializer.store(bean1, 1, 23);
		
		MyDataBean bean2 = serializer.dispense(MyDataBean.class, 1, 23); //here the error occurs

		//Close connection
		connector.close();



Connector.read/write work fine!

**Comment by a13u** [comment]
I found the error: 
I was forced to disable the DB-optimization. Then I saw that the offsets were not matching (and of course, you have to create the variables before serialization).

Thank you for your support and your effort!

**Comment by thomasrudin** [comment]
Thank you for the error-report anyway :smile: it's a  good future reference for people with the same issue.
