### ISSUE TITLE
Serialization of long String fails

### ISSUE THREAD

**Issue by a13u** [s7connector/s7connector#48]
I am using the bean method for reading a string from a S7-1200:
public class MyBean {
	@S7Variable(byteOffset=0, bitOffset=0, type=S7Type.STRING, size=254)
	public String abc;
}

In TIA, I created a data block variable of type string which got by default a size of 256 bytes. I tested my application and it works fine - I can read the string. After doing some testing I found out that strings with 128characters or less work fine. **However, if the string has more than 128 characters I get the following exception**:
Exception in thread "SPSTest" com.github.s7connector.exception.S7Exception: dispense
	at com.github.s7connector.impl.serializer.S7SerializerImpl.dispense(S7SerializerImpl.java:157)
	at myProject.base.thread.Worker.run(S7Tester.java:43)
Caused by: com.github.s7connector.exception.S7Exception: extractBytes
	at com.github.s7connector.impl.serializer.S7SerializerImpl.extractBytes(S7SerializerImpl.java:90)
	at com.github.s7connector.impl.serializer.S7SerializerImpl.dispense(S7SerializerImpl.java:155)
	... 4 more
**Caused by: java.lang.NegativeArraySizeException**
	at com.github.s7connector.impl.serializer.converter.StringConverter.extract(StringConverter.java:32)
	at com.github.s7connector.impl.serializer.S7SerializerImpl.extractBytes(S7SerializerImpl.java:70)
	... 5 more

TIA portal allows to enter strings up to 254 (?) characters but S7Connector seems to be unable to deseralize them...
Do you have a hint for me?

**Comment by a13u** [comment]
I am using TCP and my Datablock has no "optimzed access" option

**Comment by a13u** [comment]
I did some further tests. Bellow you can see my Datablock wich has exactly 3 String variables. I did not manipulate the offest and it is obvious, that each String has 256 bytes.

![untitled](https://user-images.githubusercontent.com/11412016/50631146-9f384000-0f43-11e9-8461-de0c7668f111.png)

First, I tried to serialize it using the following bean:

	@S7Variable(byteOffset=0, bitOffset=0, type=S7Type.STRING, size=256)
	public String a;


	@S7Variable(byteOffset=256, bitOffset=0, type=S7Type.STRING, size=256)
	public String b;
	

	@S7Variable(byteOffset=512, bitOffset=0, type=S7Type.STRING, size=256)
	public String c;

If I use 256 as size I get an exception: 
Caused by: java.lang.IllegalArgumentException: Result: the desired address is beyond limit for this PLC
	at com.github.s7connector.impl.S7BaseConnection.checkResult(S7BaseConnection.java:55)
	at com.github.s7connector.impl.S7BaseConnection.read(S7BaseConnection.java:101)
	at com.github.s7connector.impl.S7BaseConnection.read(S7BaseConnection.java:93)
	at com.github.s7connector.impl.S7BaseConnection.read(S7BaseConnection.java:93)
	at com.github.s7connector.impl.S7BaseConnection.read(S7BaseConnection.java:93)
	at com.github.s7connector.impl.S7BaseConnection.read(S7BaseConnection.java:93)
	at com.github.s7connector.impl.S7BaseConnection.read(S7BaseConnection.java:93)
	at com.github.s7connector.impl.S7BaseConnection.read(S7BaseConnection.java:93)
	at com.github.s7connector.impl.S7BaseConnection.read(S7BaseConnection.java:93)
	at com.github.s7connector.impl.S7BaseConnection.read(S7BaseConnection.java:93)
	at com.github.s7connector.impl.serializer.S7SerializerImpl.dispense(S7SerializerImpl.java:154)
	... 14 more

With this setup I still get an exception (size was reduced)


	@S7Variable(byteOffset=0, bitOffset=0, type=S7Type.STRING, size=255)
	public String a;


	@S7Variable(byteOffset=256, bitOffset=0, type=S7Type.STRING, size=255)
	public String b;
	

	@S7Variable(byteOffset=512, bitOffset=0, type=S7Type.STRING, size=255)
	public String c;


With a size of 254 it works:
	@S7Variable(byteOffset=0, bitOffset=0, type=S7Type.STRING, size=254)
	public String a;


	@S7Variable(byteOffset=256, bitOffset=0, type=S7Type.STRING, size=254)
	public String b;
	

	@S7Variable(byteOffset=512, bitOffset=0, type=S7Type.STRING, size=254)
	public String c;



So what does the size mean (is it in bytes? the documentation says: The specified size (for String)
)? Why does it not work if I exceed it to 256? I still have the above mentioned issue with long string...
What I am doing wrong?

**Comment by thomasrudin** [comment]
Are you having the issue when you fetch/request the entire class? (254*3 Strings)

**Comment by a13u** [comment]
Yes.
I also have it if I only use a single String the class -> I am working with the bean approach

**Comment by thomasrudin** [comment]
The following link points to the serializer for the String Type:
https://github.com/s7connector/s7connector/blob/master/src/main/java/com/github/s7connector/impl/serializer/converter/StringConverter.java#L30

**The format on the PLC:**
* Byte[0] == Overall/defined length
* Byte[1] == Current length
* Byte[2...254] == String data

**Your example:**
```java
	@S7Variable(byteOffset=0, bitOffset=0, type=S7Type.STRING, size=255)
	public String a;

	@S7Variable(byteOffset=256, bitOffset=0, type=S7Type.STRING, size=255)
	public String b;
	
	@S7Variable(byteOffset=512, bitOffset=0, type=S7Type.STRING, size=255)
	public String c;
```

This can not work with the given offsets/lengths: 
* as far as i know the string length (at least for S7-300/400) is max 254
* _String a_ would (if this were valid) occupy the byte range 0 to 257
* _String b_ would start within _String a_ (byteOffset=256)

The following example you gave should work though:
```java
	// bytes 0 ... 255
	@S7Variable(byteOffset=0, bitOffset=0, type=S7Type.STRING, size=254)
	public String a;

	// bytes 256 ... 511
	@S7Variable(byteOffset=256, bitOffset=0, type=S7Type.STRING, size=254)
	public String b;
	
	// bytes 512 ... 767
	@S7Variable(byteOffset=512, bitOffset=0, type=S7Type.STRING, size=254)
	public String c;
```

You said it yourself:
> With a size of 254 it works:

The limit of the String-length could be in theory up to 255 bytes (0xFF) but in my experience it only works up to 254 bytes.
Sadly this is a proprietary protocol and there is no spec available to look up such things :disappointed:

Let me know if you have further problems...

**Comment by a13u** [comment]
First of all: Thank you very much for this detailed and quick answer! I hope that my issue helps other users which want to support or use your library!
Now, the size attribute issue is clear for me. 
However, if I specify a class as follows then I am able to read the string if it has less than 128 characters....
```
	@S7Variable(byteOffset=0, bitOffset=0, type=S7Type.STRING, size=254)
	public String a;
```
If the string has e.g. 140 characters I get the exception above mentioned exception (Caused by: java.lang.NegativeArraySizeException). Why do I get an exception? I assume that 1byte is used per character (see e.g. [here](https://support.industry.siemens.com/tf/WW/en/posts/data-type-string-of-less-size/182799?page=0&pageSize=10) and also the TIA portal seems to allows  to enter 255 characters with the "Monitor Function")

**Comment by thomasrudin** [comment]
> if it has less than 128 
Ok, that sounds like a sign issue (byte: -128)
I'll make a testcase and fix in the next few days...
