### ISSUE TITLE
BitConverter.insert() does not handle false as bit value 0

### ISSUE THREAD

**Issue by mfriedemann** [s7connector/s7connector#50]
Hey,

the BitConverter.insert() method does not handle boolean false values, it just ignores them.
It is therefore not possible to set a bit to 0.

https://github.com/s7connector/s7connector/blob/47d4736214a22fde180a9e4d78f2ab36ecf35c69/src/main/java/com/github/s7connector/impl/serializer/converter/BitConverter.java#L57-L61

```
@Test
public void testInsertFalseBits() {
	byte[] buffer = new byte[] { 0b0101_0101 };
	int expected =               0b0101_0100;
	new BitConverter().insert(false, buffer, 0, 0, 1);
	Assert.assertEquals(expected, (int) buffer[0]);
}
```
`java.lang.AssertionError: expected:<84> but was:<85>`

Regards, M.

**Comment by mfriedemann** [comment]
Suggested fix:
```
	if (value) {
		buffer[byteOffset] |= (0x01 << bitOffset);
	} else {
		buffer[byteOffset] &= ~(0x01 << bitOffset);
	}
```

**Comment by thomasrudinzid1** [comment]
Thx for the sample and test :smile:
