### ISSUE TITLE
Connect the s7-200 family failed, because the code remove the TCP243 protocol

### ISSUE THREAD

**Issue by Seayar** [s7connector/s7connector#56]
When I user the s7connector to read/write data from the s7-200 device with the TCP protocol, the program often prompts that the socket connection failed(the pipeline broken), so I compared the source code of s7connector with libnodave and found that s7connector removed the TCP243 protocol. Now I made some changes to the latest version and made sure the s7connecor can support the s7-200 device. I tested the code on a real device and found no problems right now. So can I submit my code?

**Comment by thomasrudin** [comment]
Thx for the pull-request :smile:
looks good so far...
