### ISSUE TITLE
Java 10/Open JDK 11 support

### ISSUE THREAD

**Issue by a13u** [s7connector/s7connector#63]
Does the library support Java 10 or Open JDK? What is the recommended Java version? (haven't seen that in the docu)
As oracle introduced licensing I am especially interested in Open JDK 11 support

**Comment by thomasrudin** [comment]
The library itself does not depend upon specific jvm internals.
You may have to test it, but it should work on Java/OpenJDK 8+

**Comment by a13u** [comment]
I tested reading/writing DBs with the annotation approacch with Java 11 ([AdoptOpenJDK, ](https://adoptopenjdk.net/?variant=openjdk11&jvmVariant=hotspot)) with Hotspot. Seems to work.
PLC: S7 1200
