### ISSUE TITLE
Data Population in SPS

### ISSUE THREAD

**Issue by a13u** [s7connector/s7connector#72]
I am  using the [annotation approach](https://github.com/s7connector/s7connector/blob/master/src/test/java/com/github/s7connector/test/example/MyDataBean.java) for writing data to a datablock. When I tried the library I found out that my hardware device, which reads from that datablock, throws an error because a integer variable of that datablock is negative. Indeed, I do not set a negative value to that variable. Also in the TIA portal (monitor mode) the value is positive. For it seems like this variable is negative only for a very short time.

So I am wondering how the data is written to the datablock in the S7. Might it be possible that the data is written "byte-by-byte" so that the variable takes on negative values during the serialize process?

**Comment by thomasrudin** [comment]
It is possible that the command is not completely "atomic" if the data you are writing is larger than the block size (256 bytes i think...)

How much data are you writing and how does it look like?

**Comment by a13u** [comment]
I didn't know that atomic values are supported
So it seems that the error is in my algorithm - I will notify you as soon as I have new information

**Comment by a13u** [comment]
I think I have the problem. It is in my code. It seems like the commands com.github.s7connector.api.S7Serializer.dispense and com.github.s7connector.api.S7Serializer.store are not multi-threadable. So running one thread which executes store and a second one which executes dispense seems not lead to a better performance. This seems to be my issue. Do you have a recommendation how to improve the performance? (one read/write of a datablock takes about 50ms)

**Comment by thomasrudin** [comment]
> It seems like the commands com.github.s7connector.api.S7Serializer.dispense and com.github.s7connector.api.S7Serializer.store are not multi-threadable

I have an issue open about the documentation-rewrite, i'll add a note about that too...

> Do you have a recommendation how to improve the performance?

Not really, no. But you _could_ write simultaneously to different data-blocks, but i think the bottle-neck is the S7-CPU though... :/
