### ISSUE TITLE
Interface.write: java.net.SocketException: Software caused connection abort: socket write error

### ISSUE THREAD

**Issue by brunom1265** [s7connector/s7connector#73]
Everytime i try to run the original code that comes with the main file 

`S7Connector c = 
				S7ConnectorFactory
				.buildTCPConnector()
				.withHost("192.168.0.1")
				.build();
		
		S7Serializer s = S7SerializerFactory.buildSerializer(c);
		
		DB db = new DB();
		db.str = "Hello!";
		db.d = Math.PI;
		db.b1 = true;
		db.b3 = true;
		db.by1 = 0x5A;
		
		Date d = new Date();
		System.out.println(d);
		System.out.println(d.getTime());
		
		db.date1 = d;
		db.date2 = d;
		db.millis = 3600000;
		
		s.store(db, 100, 0);

		System.out.println("OK");
		
		c.close();`
i get this 

`Interface.write: java.net.SocketException: Software caused connection abort: socket write error
10:09:24.850 [main] TRACE c.g.s.i.serializer.parser.BeanParser - Parsing: com.github.s7connector.test.live.BigDBTest$DB
10:09:24.865 [main] TRACE c.g.s.i.serializer.parser.BeanParser - Parsing field: bytes
10:09:24.866 [main] TRACE c.g.s.i.serializer.parser.BeanParser - 		type: BYTE
10:09:24.866 [main] TRACE c.g.s.i.serializer.parser.BeanParser - 		byteOffset: 0
10:09:24.866 [main] TRACE c.g.s.i.serializer.parser.BeanParser - 		bitOffset: 0
10:09:24.866 [main] TRACE c.g.s.i.serializer.parser.BeanParser - 		size: 0
10:09:24.866 [main] TRACE c.g.s.i.serializer.parser.BeanParser - 		arraySize: 4096
10:09:24.866 [main] TRACE c.g.s.i.serializer.parser.BeanParser - 	New blocksize (+offset): 0
10:09:24.866 [main] TRACE c.g.s.i.serializer.parser.BeanParser - 	New blocksize (+array): 4096
10:09:24.866 [main] TRACE c.g.s.i.serializer.parser.BeanParser - Parsing done, overall size: 4096
10:09:24.866 [main] TRACE c.g.s.i.serializer.S7SerializerImpl - store-buffer-size: 4096
10:09:24.867 [main] TRACE c.g.s.i.serializer.S7SerializerImpl - Inerting buffer with size: 4096 at offset 0 into bean: com.github.s7connector.test.live.BigDBTest$DB@33c7e1bb
10:09:24.868 [main] TRACE c.g.s.i.serializer.parser.BeanParser - Parsing: com.github.s7connector.test.live.BigDBTest$DB
10:09:24.868 [main] TRACE c.g.s.i.serializer.parser.BeanParser - Parsing field: bytes
10:09:24.868 [main] TRACE c.g.s.i.serializer.parser.BeanParser - 		type: BYTE
10:09:24.869 [main] TRACE c.g.s.i.serializer.parser.BeanParser - 		byteOffset: 0
10:09:24.869 [main] TRACE c.g.s.i.serializer.parser.BeanParser - 		bitOffset: 0
10:09:24.869 [main] TRACE c.g.s.i.serializer.parser.BeanParser - 		size: 0
10:09:24.869 [main] TRACE c.g.s.i.serializer.parser.BeanParser - 		arraySize: 4096
10:09:24.869 [main] TRACE c.g.s.i.serializer.parser.BeanParser - 	New blocksize (+offset): 0
10:09:24.869 [main] TRACE c.g.s.i.serializer.parser.BeanParser - 	New blocksize (+array): 4096
10:09:24.869 [main] TRACE c.g.s.i.serializer.parser.BeanParser - Parsing done, overall size: 4096
Interface.write: java.net.SocketException: Software caused connection abort: socket write error
Exception in thread "main" com.github.s7connector.exception.S7Exception: store
	at com.github.s7connector.impl.serializer.S7SerializerImpl.store(S7SerializerImpl.java:187)
	at com.github.s7connector.test.live.BigDBTest.main(BigDBTest.java:59)
Caused by: java.lang.IllegalArgumentException: Result: no message defined for code: 4096!
	at com.github.s7connector.impl.S7BaseConnection.checkResult(S7BaseConnection.java:55)
	at com.github.s7connector.impl.S7BaseConnection.write(S7BaseConnection.java:124)
	at com.github.s7connector.impl.S7BaseConnection.write(S7BaseConnection.java:118)
	at com.github.s7connector.impl.serializer.S7SerializerImpl.store(S7SerializerImpl.java:185)
	... 1 more`

**Comment by a13u** [comment]
I have a similar problem. I am using a `ET200 SP ` CPU and I use S7 connector via maven:
```
		<dependency>
			<groupId>com.github.s7connector</groupId>
			<artifactId>s7connector</artifactId>
			<version>2.1</version>
		</dependency>
```

I can connect and write/write datablock using the annotation approach. So the communication works. Now, I am testing some exceptional cases. Surprisingly, when I unplug the network cable my serializer is still working:
`serializer.dispense(this.type, this.getDbnum(), this.getOffset());`
On the output line I get the following message:

> Interface.write: java.net.SocketException: Connection reset by peer: socket write error

However, the dispense does NOT throw an error. Wouldn't it be better if an error is thrown so that I can do re-connect try?

**Comment by a13u** [comment]
Probably identical to issue #55

**Comment by a13u** [comment]
Do you have 

- [ created a datablock in the SPS]
- [ deactiviated the datablock optimization in TIA]
- [ enabled PUT/GET Access in TIA ]

**Comment by moniwe** [comment]
which version of s7connector do you use? since i get "Interface.write: java.net.SocketException: Connection reset by peer: socket write error" when i try to connect to an S7-1500 with the master branch.

**Comment by a13u** [comment]
I am using version 2.1 from maven central...
