### ISSUE TITLE
WORD - INT and DWORD - DINT ranges

### ISSUE THREAD

**Issue by moniwe** [s7connector/s7connector#77]
I think that WORD and DWORD are unsigned numbers whereas INT and DINT are signed. I think it should be as [follows:](http://www.plcdev.com/step_7_elementary_data_types) 

WORD from 0 to 65.535
INT form -32.768 to 32.767
DWORD from 0 to 4.294.967.295
DINT from -2.147.483.648 to 2.147.483.647

 Is it possible that the ranges returned by the Converters are not always correct?

**Comment by thomasrudin** [comment]
> Is it possible that the ranges returned by the Converters are not always correct?

That's a possibility, yes :)
Do you have a test-case or similar for that?

**Comment by moniwe** [comment]
since I do not always have access to a PLC I made a structure representing a DB, where I put all data types in, like the following:

```
private byte[] createStructure() {
		byte[] mybyte = new byte[5408];
		StringConverter sc = new StringConverter();
...
// WORD
		IntegerConverter ic = new IntegerConverter();
		ic.insert(65535, mybyte, 1028, 0, ic.getSizeInBytes()); 
...
// DWORD
		LongConverter lc = new LongConverter();
		lc.insert(new Long("4294967294"), mybyte, 1542, 0, lc.getSizeInBytes()); 
...
// INT as WORD
		IntegerConverter ic2 = new IntegerConverter();
		ic2.insert(-32767, mybyte, 4890, 0, ic2.getSizeInBytes()); 
...
// DINT as DWORD
		LongConverter lc2 = new LongConverter();
		lc2.insert(new Long("-2147483648"), mybyte, 5404, 0, lc2.getSizeInBytes()); 

		return mybyte;
	}
```

the output i get for different inserts as described above is the following:

  | insert | extract
-- | -- | --
WORD | 0 | 0
WORD | 65.535 | 65.535
INT | 32.767 | 32.767
INT | -32.768 | **32.768**
DINT | -2.147.483.648 | -2.147.483.648
DINT | 2.147.483.647 | 2.147.483.647
DWORD | 0 | 0
DWORD | 4.294.967.296 | **0**
DWORD | 4.294.967.295 | **-1**

**Comment by moniwe** [comment]
Siemens states this:

Type | lower range | upper range
-- | -- | --
[DWORD](https://support.industry.siemens.com/cs/mdm/109755202?c=101392416907&lc=en-CN) | -2.147.483.647 | 2.147.483.647
  | 0 | 4.294.967.295
[WORD](https://support.industry.siemens.com/cs/mdm/109755202?c=86295353739&lc=en-CN) | -32.768 | 32.767
  | 0 | 65.535
[DINT](https://support.industry.siemens.com/cs/mdm/109755202?c=85665029899&lc=en-CN) | -2.147.483.648 | 2.147.483.647
[INT ](https://support.industry.siemens.com/cs/mdm/109755202?c=112471435147&lc=en-CN) | -32.768 | 32.767

seems that word and dword are allowed to use unsigned and signed numbers

**Comment by thomasrudin** [comment]
Thanks for your help :+1:
