### ISSUE TITLE
Inconsistent API and broken OSGi support

### ISSUE THREAD

**Issue by AntosDR** [s7connector/s7connector#85]
The API enumeration
https://github.com/s7connector/s7connector/blob/cbe3455952dc1e4adf4e1de8d54d7303cb7d34f8/src/main/java/com/github/s7connector/api/annotation/S7Variable.java#L34 refers the enum type https://github.com/s7connector/s7connector/blob/cbe3455952dc1e4adf4e1de8d54d7303cb7d34f8/src/main/java/com/github/s7connector/api/annotation/S7Variable.java#L58 which is instead defined in the private package `com.github.s7connector.impl.utils`. This means that using the `S7Variable` annotation automatically implies the linking of the private type `S7Type` from your own code. Using the bundle in a standalone application will still work but if you try to use the library in an OSGi environment (e.g. Apache Karaf) the following unsatisfied dependency occurs:
`Error starting bundle <<my bundle number>>: Unable to resolve <<my bundle>>: missing requirement [<<my bundle>>] osgi.wiring.package; (osgi.wiring.package=com.github.s7connector.impl.utils) Unresolved requirements: [[<<my bundle>>] osgi.wiring.package; (osgi.wiring.package=com.github.s7connector.impl.utils)]` 
This error tells the user that its bundle has linked a class of the `com.github.s7connector.impl.utils`, (the S7Type in this case) which is a private package and this is not allowed. 
The `maven-bundle-plugin` in the pom.xml does not include any export directive and therefore each package with name `*.impl.*` or `*.internal.*` is implicitly private.
Event if in a standalone application this will still work, the API definition is still inconsistent and should be corrected moving the S7Type in the `api` package.

Thank you.

**Comment by thomasrudin** [comment]
Thanks for spotting that, but i'm afraid i'm not actively maintaining this project anymore (see #74).
Feel free to open a PR or volunteer as maintainer.. :smile:
