### ISSUE TITLE
S7 400H - Rack 1 - Cant'read data

### ISSUE THREAD

**Issue by redsoft7** [s7connector/s7connector#91]
Reading from a S7 400H from **rack 1** I get the following error:

```
java.lang.IllegalArgumentException: Result: Unexpected function code in answer
	at com.github.s7connector.impl.S7BaseConnection.checkResult(S7BaseConnection.java:55)
	at com.github.s7connector.impl.S7BaseConnection.read(S7BaseConnection.java:101)
	at com.github.s7connector.impl.S7BaseConnection.read(S7BaseConnection.java:90)
```

Reading instead from rack 0 works correctly.

**Comment by redsoft7** [comment]
After some analysis with Wireshark I found the problem.

The library, in the TCPConnection class, sets the "rack" and the "slot" in two different bytes:
```
	this.msgOut[17] = (byte) (this.rack + 1);
	this.msgOut[18] = (byte) this.slot;
```

According to this [guide](https://www.tanindustrie.de/es/Help/ConfigClient/tsap_s7.htm) the rack and the slot both go in byte 18, while byte 17 contains the device id.

By modifying the TCPConnection class in the following way I am able to connect:
```
        this.msgOut[17] = 1;
        this.msgOut[18] = (byte) ((16 * (this.rack *2) ) +this.slot);
```

There was already an [issue]( https://sourceforge.net/p/libnodave/bugs/16/) related to this problem on the "nodave" library.

**Comment by BuckarooBanzay** [comment]
nice, thanks for debugging that :+1: 

> By modifying the TCPConnection class in the following way I am able to connect:

Are you able to whip up  a PR by any chance?

**Comment by DaoshunShi** [comment]
It seems that this fix doesn't publish to maven nexus repository.

**Comment by BuckarooBanzay** [comment]
> It seems that this fix doesn't publish to maven nexus repository.

See #74 (this is my new github account btw) i currently don't have time and interest to pursue this project any further, if anyone wants to adopt this feel free to contact me :+1:
